#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running validations before commit..."

./valid.bat
STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "Validation failed! Commit aborted."
  echo "To skip validation, use: git commit --no-verify -m 'Message' "
  exit 1
fi
